<?php

namespace Database\Seeders\Support;

/**
 * کاتالوگ محصولات نمایشی — هر محصول نام واقعی و توضیحات فروشگاهی دارد.
 * تصاویر از {@see \App\Support\ProductImages} بر اساس SKU و نام محصول انتخاب می‌شوند.
 */
class DemoProductCatalog
{
    /**
     * @return array<int, array{
     *     sku: string,
     *     slug: string,
     *     name: string,
     *     brand_slug: string,
     *     category: string,
     *     short_description: string,
     *     description: string,
     *     is_featured?: bool,
     *     is_active?: bool,
     *     sizes?: array<int, string>|null,
     *     colors?: array<int, string>|null,
     * }>
     */
    public static function products(): array
    {
        return [
            [
                'sku' => 'SKU-00001',
                'slug' => 'samsung-side-by-side-refrigerator-26ft',
                'name' => 'یخچال ساید بای ساید سامسونگ ۲۶ فوت',
                'brand_slug' => 'samsung',
                'category' => 'لوازم خانگی',
                'short_description' => 'یخچال دوقلو با کمپرسور اینورتر و نوآر فریزر',
                'description' => 'یخچال ساید بای ساید سامسونگ با ظرفیت ۲۶ فوت، طراحی مدرن استیل، یخ‌ساز اتوماتیک و مصرف انرژی بهینه.',
                'is_featured' => true,
            ],
            [
                'sku' => 'SKU-00002',
                'slug' => 'mens-wool-coat-black',
                'name' => 'کاپشن مردانه پشمی مشکی',
                'brand_slug' => 'nike',
                'category' => 'پوشاک',
                'short_description' => 'کاپشن گرم و شیک مناسب فصل پاییز و زمستان',
                'description' => 'کاپشن مردانه از پارچه پشمی با آستر گرم، دوخت تمیز و مناسب استفاده روزمره و مهمانی.',
                'is_featured' => true,
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['مشکی', 'خاکستری'],
            ],
            [
                'sku' => 'SKU-00003',
                'slug' => 'book-one-hundred-years-of-solitude',
                'name' => 'کتاب صد سال تنهایی اثر گابریل گارسیا مارکیز',
                'brand_slug' => 'ibm',
                'category' => 'کتاب',
                'short_description' => 'رمان کلاسیک برنده نوبل ادبیات',
                'description' => 'چاپ با کیفیت و ترجمه روان. مناسب علاقه‌مندان به ادبیات کلاسیک آمریکای لاتین.',
                'is_featured' => true,
            ],
            [
                'sku' => 'SKU-00004',
                'slug' => 'sony-playstation-5',
                'name' => 'کنسول بازی سونی پلی‌استیشن ۵',
                'brand_slug' => 'sony',
                'category' => 'لوازم الکترونیکی',
                'short_description' => 'کنسول نسل نهم با گرافیک 4K و SSD فوق‌سریع',
                'description' => 'پلی‌استیشن ۵ با دسته DualSense، پشتیبانی از ری‌تریسینگ و بارگذاری سریع بازی‌ها.',
                'is_featured' => true,
            ],
            [
                'sku' => 'SKU-00005',
                'slug' => 'skincare-moisturizer-set',
                'name' => 'ست مرطوب‌کننده و سرم آبرسان پوست',
                'brand_slug' => 'xiaomi',
                'category' => 'آرایشی بهداشتی',
                'short_description' => 'مراقبت روزانه پوست خشک و حساس',
                'description' => 'شامل کرم مرطوب‌کننده و سرم هیالورونیک اسید برای آبرسانی عمیق و درخشندگی پوست.',
                'is_featured' => true,
            ],
            [
                'sku' => 'SKU-00006',
                'slug' => 'dumbbell-set-10kg',
                'name' => 'ست دمبل ورزشی ۱۰ کیلوگرمی',
                'brand_slug' => 'adidas',
                'category' => 'ورزشی',
                'short_description' => 'دمبل روکش‌دار مناسب تمرین خانگی',
                'description' => 'ست دمبل ۱۰ کیلوگرمی با روکش لاستیکی ضد لغزش، مناسب بدنسازی و تناسب اندام در منزل.',
                'is_featured' => true,
            ],
            [
                'sku' => 'SKU-00007',
                'slug' => 'lego-building-blocks-1000pcs',
                'name' => 'پازل ساختنی لگو ۱۰۰۰ قطعه',
                'brand_slug' => 'puma',
                'category' => 'اسباب‌بازی',
                'short_description' => 'اسباب‌بازی آموزشی برای تقویت خلاقیت کودکان',
                'description' => 'مجموعه ۱۰۰۰ قطعه‌ای بلوک‌های ساختنی با راهنمای مونتاژ، مناسب کودکان بالای ۶ سال.',
                'is_featured' => true,
            ],
            [
                'sku' => 'SKU-00008',
                'slug' => 'stationery-pen-notebook-set',
                'name' => 'ست خودکار و دفتر یادداشت A5',
                'brand_slug' => 'lenovo',
                'category' => 'لوازم التحریر',
                'short_description' => 'لوازم التحریر با کیفیت برای دانش‌آموز و اداری',
                'description' => 'شامل دفتر A5 خط‌دار، خودکار ژل و مداد طراحی. بسته‌بندی مناسب هدیه.',
                'is_featured' => true,
            ],
            [
                'sku' => 'SKU-00009',
                'slug' => 'apple-iphone-15-pro',
                'name' => 'گوشی اپل آیفون ۱۵ پرو ۲۵۶ گیگابایت',
                'brand_slug' => 'apple',
                'category' => 'کالای دیجیتال',
                'short_description' => 'پرچمدار اپل با تراشه A17 Pro و دوربین پیشرفته',
                'description' => 'آیفون ۱۵ پرو با بدنه تیتانیوم، نمایشگر ProMotion و دوربین ۴۸ مگاپیکسلی.',
                'is_featured' => true,
                'colors' => ['مشکی', 'سفید', 'آبی'],
            ],
            [
                'sku' => 'SKU-00010',
                'slug' => 'stainless-steel-cookware-5pc',
                'name' => 'ست قابلمه استیل ضدزنگ ۵ پارچه',
                'brand_slug' => 'lg',
                'category' => 'خانه و آشپزخانه',
                'short_description' => 'ظروف پخت با کیفیت برای آشپزخانه مدرن',
                'description' => 'ست ۵ پارچه قابلمه و تابه استیل با درب شیشه‌ای، مناسب انواع پخت‌وپز روزانه.',
                'is_featured' => true,
            ],
            [
                'sku' => 'SKU-00011',
                'slug' => 'cordless-drill-18v',
                'name' => 'دریل شارژی ۱۸ ولت حرفه‌ای',
                'brand_slug' => 'asus',
                'category' => 'ابزار و یراق',
                'short_description' => 'ابزار قدرتمند برای تعمیرات خانگی و صنعتی',
                'description' => 'دریل شارژی ۱۸ ولت با دو باتری لیتیومی، ۱۵ سطح گشتاور و چراغ LED.',
            ],
            [
                'sku' => 'SKU-00012',
                'slug' => 'gold-necklace-18k',
                'name' => 'گردنبند طلا ۱۸ عیار زنانه',
                'brand_slug' => 'google',
                'category' => 'زیورآلات',
                'short_description' => 'زیورآلات ظریف با طراحی مدرن',
                'description' => 'گردنبند طلا ۱۸ عیار با زنجیر ظریف و آویز مینیمال، مناسب استفاده روزانه و مهمانی.',
            ],
            [
                'sku' => 'SKU-00013',
                'slug' => 'nike-air-max-90',
                'name' => 'کفش ورزشی نایکی ایر مکس ۹۰',
                'brand_slug' => 'nike',
                'category' => 'کفش',
                'short_description' => 'کفش اسپرت کلاسیک با کفی راحت',
                'description' => 'نایکی ایر مکس ۹۰ با طراحی آیکونیک، کفی Air و مناسب پیاده‌روی و ورزش روزانه.',
                'sizes' => ['۴۰', '۴۱', '۴۲', '۴۳', '۴۴'],
                'colors' => ['مشکی', 'سفید', 'قرمز'],
            ],
            [
                'sku' => 'SKU-00014',
                'slug' => 'apple-watch-series-9',
                'name' => 'ساعت هوشمند اپل واچ سری ۹',
                'brand_slug' => 'apple',
                'category' => 'ساعت',
                'short_description' => 'ساعت هوشمند با سنسور سلامت پیشرفته',
                'description' => 'اپل واچ سری ۹ با نمایشگر Always-On، اندازه‌گیری اکسیژن خون و مقاومت در برابر آب.',
                'is_featured' => true,
                'colors' => ['مشکی', 'نقره‌ای'],
            ],
            [
                'sku' => 'SKU-00015',
                'slug' => 'dior-sauvage-perfume',
                'name' => 'عطر مردانه ساواج دیور ۱۰۰ میلی‌لیتر',
                'brand_slug' => 'ibm',
                'category' => 'عطر و ادکلن',
                'short_description' => 'رایحه مردانه خنک و ماندگار',
                'description' => 'ادکلن مردانه ساواج با نت‌های چوبی و ادویه‌ای، مناسب استفاده روزانه و مجلسی.',
            ],
            [
                'sku' => 'SKU-00016',
                'slug' => 'lg-washing-machine-9kg',
                'name' => 'ماشین لباسشویی ال‌جی ۹ کیلوگرم',
                'brand_slug' => 'lg',
                'category' => 'لوازم خانگی',
                'short_description' => 'لباسشویی اینورتر با ۱۴ برنامه شستشو',
                'description' => 'ماشین لباسشویی ال‌جی ۹ کیلو با موتور اینورتر کم‌صدا، شستشوی بخار و مصرف انرژی A++.',
            ],
            [
                'sku' => 'SKU-00017',
                'slug' => 'asus-rog-gaming-laptop',
                'name' => 'لپ‌تاپ گیمینگ ایسوس روگ استریكس',
                'brand_slug' => 'asus',
                'category' => 'کالای دیجیتال',
                'short_description' => 'لپ‌تاپ قدرتمند برای بازی و طراحی',
                'description' => 'ایسوس روگ با پردازنده Intel Core i7، کارت گرافیک RTX و نمایشگر ۱۴۴ هرتز.',
                'is_featured' => true,
            ],
            [
                'sku' => 'SKU-00018',
                'slug' => 'sony-wh-1000xm5-headphones',
                'name' => 'هدفون بی‌سیم سونی WH-1000XM5',
                'brand_slug' => 'sony',
                'category' => 'لوازم الکترونیکی',
                'short_description' => 'هدفون نویزکنسلینگ حرفه‌ای',
                'description' => 'هدفون سونی WH-1000XM5 با حذف نویز فعال، باتری ۳۰ ساعته و کیفیت صدای Hi-Res.',
                'is_active' => false,
            ],
        ];
    }
}
